service: bsale-store-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2

functions:
  getCategories:
    handler: src/services/getCategories.handler
    events:
      - httpApi:
          path: /categories
          method: get
  getProductsByCategory:
    handler: src/services/getProductsByCategory.handler
    events:
      - httpApi:
          path: /products/categories/{categoryId}
          method: get

custom:
  bundle:
    externals:
      - serverless-mysql

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-auto-swagger
